### PR TITLE
Fix template scanning in Jar files. Fixes #254.

### LINKED ISSUE #254: Fix template scanning in Jar files
The GraalVM workaround at https://github.com/microsoft/NubesGen/pull/238 caused the prod server to crash as we're using a Jar package.
cc @bnasslahsen

### PR DESCRIPTION
**Pull request by bnasslahsen**
This is a simple fix for the scanning in Jar files.

### CODE REVIEW

File: rest-server/src/main/java/io/github/nubesgen/utils/ResourceScannerUtils.java [hunk 1]
```diff
@@ -41,11 +42,16 @@ private ResourceScannerUtils() {
...
 	public static Resource[] getResourceFiles(ResourcePatternResolver resolver, String locationDir,
 			Predicate<Resource> directoryPredicate) throws IOException {
-		Resource[] resourcesArray = resolver.getResources(locationDir);
-		Set<Resource> resourceSet = new LinkedHashSet<>();
-		for (Resource resource : resourcesArray)
-			resourceSet.addAll(getResourceFilesRecursively(resource, resourceSet, directoryPredicate));
-		return resourceSet.toArray(new Resource[0]);
+		Resource[] resources = resolver.getResources(locationDir + "/**");
+		if (!ObjectUtils.isEmpty(resources))
+			return resources;
```
Comment (jdubois) [inline rest-server/src/main/java/io/github/nubesgen/utils/ResourceScannerUtils.java:47]: Ah ah that's smart!!!

**Comment by cmaneu** [comment]
@jdubois can we merge it?

**Comment by jdubois** [comment]
@cmaneu I believe it's good, but I also need time to test it first
